OPERA_categories = ["Royal", "Cotton", "Harley", "Lansdowne", "Arundel", "Burney", "Sloane", "Additional", "Egerton"]
OPERA_count = [36 + 48 + 19, 25 + 45 + 22, 17 + 46 + 36, 6 + 7, 21, 6, 2 + 15, 25 + 44 + 45 + 35, 6]


CORRESPONDENCE_OPERA_MSS = dict(zip(OPERA_categories, [{}]*len(OPERA_categories)))


# Dictionnaire des manuscrits extraits par LLM/VLM (Gemini)
# finalement même pas complet, donc fait à la main...
# Ajouter a fortiori tous les "mss": "...."
CORRESPONDENCE_OPERA_CORRECTED_MSS = {
    "Royal": [ 
        {"name": "Historia Regum Britannia", "page": 227}, 
        {"name": "Turpin's Chronicle", "page": 583}, 
        {"name": "Prophecy of Merlin Silvester", "page": 313}, 
        {"name": "Dares Phrygius", "page": 17}, 
        {"name": "Letters between Alexander and Dindimus", "page": 138}, 
        {"name": "Letters between Alexander and Dindimus", "page": 137},
        {"name": "Alexandreis", "page": 98}, 
        {"name": "Prophecies of Merlin", "page": 297}, 
        {"name": "Guy of Warwick", "page": 485}, 
        {"name": "Prophecy on Scotland", "page": 327}, 
        {"name": "Alexander the Great", "page": 112}, 
        {"name": "Fulk Fitz-Warin", "page": 501}, 
        {"name": "Amys and Amylion", "page": 674}, 
        {"name": "Tale of Two Lovers", "page": 801}, 
        {"name": "Historia Trojana", "page": 49}, 
        {"name": "Story of Troy", "page": 34}, 
        {"name": "Prophecy of the Tenth Sibyl", "page": 194}, 
        {"name": "Karolellus", "page": 594}, 
        {"name": "Roman de Brut", "page": 264}, 
        {"name": "Havelok", "page": 423}, 
        {"name": "Vita Merlini", "page": 289}, 
        {"name": "Apollonius of Tyre", "page": 170}, 
        {"name": "Le Chemin de Vaillance", "page": 895}, 
        {"name": "Livre de l'Ordre de Chevalerie", "page": 922}, 
        {"name": "Saint Graal", "page": 341}, 
        {"name": "Lancelot du Lac", "page": 354}, 
        {"name": "Perceforest", "page": 377}, 
        {"name": "Simon de Pouille", "page": 627}, 
        {"name": "Aspremont", "page": 598}, 
        {"name": "Fierabras", "page": 615}, 
        {"name": "Ogier le Danois", "page": 604}, 
        {"name": "Quatre fils Aimon", "page": 622}, 
        {"name": "Pontus and Sidoine", "page": 469}, 
        {"name": "Knight of the Swan", "page": 708}, 
        {"name": "Iliaca", "page": 2}, 
        {"name": "Heroica", "page": 1}, 
        {"name": "Titus and Vespasian", "page": 176}, 
        {"name": "Sydrac and Boctus", "page": 914}, 
        {"name": "Sir Gowghter", "page": 419}, 
        {"name": "Tale of Gamelyn", "page": 515}, 
        {"name": "Recueil des Histoires de Troie", "page": 64}, 
        {"name": "Mélusine", "page": 690}, 
        {"name": "Troy Book", "page": 81}, 
        {"name": "Romance of Thebes", "page": 90}, 
        {"name": "Roman de la Rose", "page": 885}, 
        {"name": "La Vengeance d'Alexandre", "page": 143}, 
        {"name": "Guillaume d'Orange", "page": 654}, 
        {"name": "Cleriadus et Meliadice", "page": 883}, 
        {"name": "Tristram", "page": 361} 
    ],
    
    "Cotton": [ 
        {"name": "Prophecies of Merlin", "page": 299}, 
        {"name": "Gesta Regum Britanniæ", "page": 274}, 
        {"name": "Vita Merlini", "page": 289}, 
        {"name": "Troy Book", "page": 75}, 
        {"name": "Sir Eglamour of Artois", "page": 766}, 
        {"name": "Octavian the Emperor", "page": 762}, 
        {"name": "Sir Launfal", "page": 416}, 
        {"name": "Lybeaus Desconus", "page": 400}, 
        {"name": "Emare", "page": 418}, 
        {"name": "Titus and Vespasian", "page": 180}, 
        {"name": "Knight of the Swan", "page": 710}, 
        {"name": "Sir Isumbras", "page": 760}, 
        {"name": "Lazamon's Brut", "page": 268}, 
        {"name": "Prophecy of the Tenth Sibyl", "page": 195}, 
        {"name": "Turpin's Chronicle", "page": 561}, 
        {"name": "Dares Phrygius", "page": 22}, 
        {"name": "Sir Gawain and the Green Knight", "page": 387}, 
        {"name": "Historia Regum Britannie", "page": 230}, 
        {"name": "Alexander the Great", "page": 113}, 
        {"name": "Story of Albina and her Sisters", "page": 199}, 
        {"name": "Petit Jean de Saintré", "page": 775}, 
        {"name": "Floridam and Elluide", "page": 779}, 
        {"name": "Ywain and Gawain", "page": 392}, 
        {"name": "Marvels of India", "page": 134}, 
        {"name": "Floyres and Blancheflur", "page": 716}, 
        {"name": "Thomas of Erceldoune", "page": 330}, 
        {"name": "Ipomedon", "page": 728}, 
        {"name": "Lanval", "page": 415}, 
        {"name": "Fall of Troy", "page": 31}, 
        {"name": "Whole Prophecy of Scotland", "page": 337}, 
        {"name": "Battle of Roncevaux", "page": 630}, 
        {"name": "Brut y Brenhinoedd", "page": 255}, 
        {"name": "Meriadoc and Gawain", "page": 374}, 
        {"name": "Romance of Thebes", "page": 91} 
    ],
    
    "Harley": [ 
        {"name": "Tristram", "page": 358}, 
        {"name": "Historia Trojana", "page": 52}, 
        {"name": "Turpin's Chronicle", "page": 574}, 
        {"name": "Historia Regum Britannie", "page": 222}, 
        {"name": "The Three Kings' Sons", "page": 782}, 
        {"name": "Romance of Troy", "page": 84}, 
        {"name": "King Robert of Sicily", "page": 765}, 
        {"name": "Gui de Bourgogne", "page": 630}, 
        {"name": "Alexander the Great", "page": 113}, 
        {"name": "King Horn", "page": 468}, 
        {"name": "Dares Phrygius", "page": 20}, 
        {"name": "Vita Merlini", "page": 288}, 
        {"name": "Story of Albina and her Sisters", "page": 201}, 
        {"name": "Lays of Marie de France", "page": 407}, 
        {"name": "Sydrac and Boctus", "page": 912}, 
        {"name": "Troilus and Cryseyde", "page": 73}, 
        {"name": "Guillaume d'Orange", "page": 660}, 
        {"name": "Chanson de Brut", "page": 272}, 
        {"name": "Prophecies de Merlin", "page": 373}, 
        {"name": "Tale of Gamelyn", "page": 513}, 
        {"name": "Tale of Two Lovers", "page": 799}, 
        {"name": "Ipomedon", "page": 755}, 
        {"name": "Morte Arthur", "page": 405}, 
        {"name": "Six Fabliaux", "page": 813}, 
        {"name": "Amys and Amylion", "page": 677}, 
        {"name": "Aronus and Marina", "page": 797}, 
        {"name": "Fall of Troy", "page": 32}, 
        {"name": "Filocolo", "page": 725}, 
        {"name": "Dictys Cretensis", "page": 11}, 
        {"name": "Corbaccio", "page": 794}, 
        {"name": "Fiammetta", "page": 793}, 
        {"name": "Life of Harold, King of England", "page": 941}, 
        {"name": "Sir Orpheo", "page": 171}, 
        {"name": "Tale of Antiochus", "page": 798}, 
        {"name": "Florimont", "page": 159}, 
        {"name": "Vœux du Paon", "page": 154}, 
        {"name": "L'Ordène de Chevalerie", "page": 810}, 
        {"name": "Girard de Roussillon", "page": 663}, 
        {"name": "Doon de la Roche", "page": 671}, 
        {"name": "Enfances Ogier", "page": 610}, 
        {"name": "Roman de Troie", "page": 35}, 
        {"name": "Richard Cœur-de-Lion", "page": 949}, 
        {"name": "Alexandreis", "page": 103}, 
        {"name": "Iliaca", "page": 8}, 
        {"name": "Merlin", "page": 885}, 
        {"name": "Theagenes and Stelliana", "page": 795} 
    ],

    "Lansdowne": [ 
        {"name": "Kings of Britain", "page": 251}, 
        {"name": "Historia Trojana", "page": 61}, 
        {"name": "Florence de Rome", "page": 711}, 
        {"name": "Abridgement of Historia Trojana", "page": 59}, 
        {"name": "Chanson de Roland", "page": 631}, 
        {"name": "Guy of Warwick", "page": 496}, 
        {"name": "Historia Regum Britannisæ", "page": 233}, 
        {"name": "Lancelot du Lac", "page": 347}, 
        {"name": "Thomas of Erçeldoune", "page": 331}, 
        {"name": "Amadis de Gaula", "page": 787}, 
        {"name": "Chanson d'Aspremont", "page": 600}, 
        {"name": "Sydrac and Boctus", "page": 915}, 
        {"name": "Tale of Gamelyn", "page": 512} 
    ],

    "Arundel": [ 
        {"name": "Historia Trojana", "page": 60}, 
        {"name": "Historia Regum Britannise", "page": 224}, 
        {"name": "Prophecies of Merlin, Gildas, and Thomas of Ercildoune", "page": 307}, 
        {"name": "Prophecies of Merlin", "page": 301}, 
        {"name": "Troy Book", "page": 80}, 
        {"name": "Romance of Thebes", "page": 87}, 
        {"name": "Apollonius of Tyre", "page": 164}, 
        {"name": "Alexander the Great", "page": 120}, 
        {"name": "Letter of Dindimus to Alexander the Great", "page": 140}, 
        {"name": "Birth of Merlin", "page": 384}, 
        {"name": "Turpin's Chronicle", "page": 589}, 
        {"name": "Vœux du Paon", "page": 155}, 
        {"name": "Marvels of India", "page": 133}, 
        {"name": "Treatise on the Brahmins", "page": 134} 
    ],

    "Burney": [ 
        {"name": "Dictys Cretensis", "page": 9}, 
        {"name": "History of Troy", "page": 66}, 
        {"name": "Dares Phrygius", "page": 16}, 
        {"name": "Alexander the Great", "page": 118}, 
        {"name": "Alexandreis", "page": 101} 
    ],

    "Sloane": [ 
        {"name": "Historia Regum Britannisæ", "page": 250}, 
        {"name": "Cassandra", "page": 803}, 
        {"name": "Life of Robin Hood", "page": 517}, 
        {"name": "Quatre fils Aimon", "page": 624}, 
        {"name": "Guy of Warwick", "page": 489}, 
        {"name": "Alexander the Great", "page": 112}, 
        {"name": "Apollonius of Tyre", "page": 161}, 
        {"name": "Dares Phrygius", "page": 19}, 
        {"name": "Tale of Gamelyn", "page": 514}, 
        {"name": "Whole Prophecy of Scotland", "page": 334}, 
        {"name": "Sydrac and Boctus", "page": 919}, 
        {"name": "Collection of Prophecies", "page": 833}, 
        {"name": "Robyn and Gandelyn", "page": 516}, 
        {"name": "Letter of Dindimus to Alexander the Great", "page": 140} 
    ],

    "Additional": [ 
        {"name": "Apollonius of Tyre", "page": 167}, 
        {"name": "Five Romantic Tales", "page": 841}, 
        {"name": "Ívents saga", "page": 393}, 
        {"name": "Eight Romantic Tales", "page": 843}, 




























        
        {"name": "Parcevals saga and Valvers þáttr", "page": 395}, 
        {"name": "Ereks saga Artuskappa", "page": 403}, 
        {"name": "Möttuls saga", "page": 405}, 
        {"name": "Life of Virgilius", "page": 196}, 
        {"name": "Eight Romantic Tales", "page": 846, "mss": ""},
        {"name": "Magus saga Jarls", "page": 686, "mss": ""},
        {"name": "Partalopa saga", "page": 707, "mss": ""},
        {"name": "Seven Romantic Tales", "page": 847, "mss": ""},
        {"name": "Samsons saga Fagra", "page": 407, "mss": ""},
        {"name": "Apollonius of Tyre", "page": 168, "mss": ""},
        {"name": "Magus saga Jarls", "page": 686}, 
        {"name": "Partalópa saga", "page": 707}, 
        {"name": "Seven Romantic Tales", "page": 847}, 
        {"name": "Samsons saga Fagra", "page": 407}, 
        {"name": "Trójumanna saga", "page": 62}, 
        {"name": "Magus saga Jarls", "page": 684, "mss": ""},
        {"name": "Two Romantic Tales", "page": 850, "mss": ""},
        {"name": "Three Romantic Tales", "page": 851, "mss": ""},
        {"name": "Magus saga Jarls", "page": 688, "mss": ""},
        {"name": "Three Romantic Tales", "page": 852, "mss": ""},
        {"name": "Three Romantic Tales", "page": 854}, 
        {"name": "Saga of Ajax Frækni", "page": 854}, 
        {"name": "Tristram", "page": 359}, 
        {"name": "Merlínus Spá", "page": 304}, 
        {"name": "Mélusine", "page": 692}, 
        {"name": "Prophecies of Merlin", "page": 304}, 
        {"name": "Turpin's Chronicle", "page": 583}, 
        {"name": "Historia Trojana", "page": 57}, 
        {"name": "Titus and Vespasian", "page": 187}, 
        {"name": "Dares Phrygius", "page": 24}, 
        {"name": "Sydrac and Boctus", "page": 921}, 
        {"name": "Titus and Vespasian", "page": 179, "mss": ""},
        {"name": "Juglet", "page": 812}, 
        {"name": "Romance of Jason", "page": 92}, 
        {"name": "Saint Graal", "page": 340}, 
        {"name": "Merlin", "page": 343}, 
        {"name": "Lancelot du Lac", "page": 352}, 
        {"name": "Artus de Bretagne", "page": 382}, 
        {"name": "Filocolo", "page": 724}, 
        {"name": "Ricciardetto", "page": 680}, 
        {"name": "Aspramonte", "page": 602}, 
        {"name": "Romance of the Peers of France", "page": 682}, 
        {"name": "Rimur of Remund", "page": 855}, 
        {"name": "Rímur from Trójumanna saga", "page": 63}, 
        {"name": "Life of Virgilius", "page": 197, "mss": ""},
        {"name": "Collection of Anecdotes", "page": 855}, 
        {"name": "Gabons saga ok Vigoles", "page": 402}, 
        {"name": "Valentine and Orson and Tales", "page": 857}, 
        {"name": "Ten Romantic Tales", "page": 858}, 
        {"name": "Patient Griselda", "page": 865}, 
        {"name": "Argenis", "page": 866}, 
        {"name": "Merlinus Spa", "page": 307, "mss": ""},
        {"name": "Alexanders saga", "page": 104}, 
        {"name": "Two Romantic Tales", "page": 867, "mss": ""},
        {"name": "Petit Jean de Saintré", "page": 778}, 
        {"name": "Historia Regum Britannia", "page": 247}, 
        {"name": "Roman de la Rose", "page": 887}, 
        {"name": "Troilus and Cryseyde", "page": 71}, 
        {"name": "Uberto and Philomena", "page": 784}, 
        {"name": "Turpin's Chronicle", "page": 562, "mss": ""},
        {"name": "Itinerary to Compostella", "page": 951}, 
        {"name": "Meliadus", "page": 364}, 
        {"name": "Roman d'Eneas", "page": 82}, 
        {"name": "Guy of Warwick", "page": 490}, 
        {"name": "Filocolo", "page": 716, "mss": ""},
        {"name": "Hanes Taliesin", "page": 421}, 
        {"name": "Brut Gruffydd ap Arthur", "page": 258}, 
        {"name": "Peredur ab Efrawc", "page": 395},
        {"name": "Hanes Taliesin", "page": 422, "mss": ""},
        {"name": "Extracts from Brut y Brenhinoedd", "page": 259, "mss": ""},
        {"name": "Iarlles y Ffynnawn", "page": 393, "mss": ""},
        {"name": "Dares Phrygius", "page": 25, "mss": ""},
        {"name": "Contes et Fabliaux", "page": 804, "mss": ""},
        {"name": "Partonopeus de Blois", "page": 698, "mss": ""},
        {"name": "Blanchandin et Orgueillose d'Amors", "page": 727, "mss": ""},
        {"name": "Floire et Blancheflor", "page": 714, "mss": ""},
        {"name": "Dictys Cretensis", "page": 10, "mss": ""},
        {"name": "Historia Trojana", "page": 43, "mss": ""},
        {"name": "Brut Tysilio", "page": 254, "mss": ""},
        {"name": "Les deux Chevaliers, and Le dit de Guillaume d'Angleterre", "page": 757, "mss": ""},
        {"name": "Historia Regum Britanniae", "page": 234, "mss": ""},
        {"name": "Roman de la Rose", "page": 894, "mss": ""},
        {"name": "Roman d'Athis et Profilias", "page": 173, "mss": ""},
        {"name": "Roman d'Athis et Profilias", "page": 929, "mss": ""},
        {"name": "Sydrac and Boctus", "page": 903, "mss": ""},
        {"name": "Voeux du Paon and Restor du Paon", "page": 150, "mss": ""},
        {"name": "Theseus de Cologne", "page": 769, "mss": ""},
        {"name": "Voeux du Paon", "page": 146, "mss": ""},
        {"name": "Alexandreis", "page": 141, "mss": ""},
        {"name": "Lancelot du Lac", "page": 348, "mss": ""},
        {"name": "Sydrac and Boctus", "page": 909, "mss": ""},
        {"name": "Turpin's Chronicle", "page": 592, "mss": ""},
        {"name": "Alexandreis", "page": 99, "mss": ""},
        {"name": "Romance of Thebes", "page": 89, "mss": ""},
        {"name": "The Diana of Montemayor", "page": 789, "mss": ""},
        {"name": "Amis and Amylion", "page": 678, "mss": ""},
        {"name": "Turpin's Chronicle", "page": 573, "mss": ""},
        {"name": "Wigalois", "page": 398, "mss": ""},
        {"name": "Iwein", "page": 390, "mss": ""},
        {"name": "Dares Phrygius", "page": 26, "mss": ""},
        {"name": "Brut Gruffydd ap Arthur", "page": 257, "mss": ""},
        {"name": "May Colvin", "page": 544, "mss": ""},
        {"name": "Philomena", "page": 596, "mss": ""},
        {"name": "Filostrato", "page": 67, "mss": ""},
        {"name": "Historia Trojana", "page": 46, "mss": ""},
        {"name": "King Robert of Sicily", "page": 763, "mss": ""},
        {"name": "The King of Tars and the Soudan of Damas", "page": 767, "mss": ""},
        {"name": "Scottish Ballads", "page": 531, "mss": ""},
        {"name": "Reali di Francia", "page": 672, "mss": ""},
        {"name": "Alexandreis", "page": 96, "mss": ""},
        {"name": "Tristram", "page": 357, "mss": ""},
        {"name": "Guiron le Courtois", "page": 369, "mss": ""},
        {"name": "Tales and Fables", "page": 826, "mss": ""},
        {"name": "Nine Romantic Tales", "page": 867, "mss": ""},
        {"name": "Alexanders saga", "page": 105, "mss": ""},
        {"name": "Story of Sigurgaror", "page": 871, "mss": ""},
        {"name": "Fertrams saga", "page": 872, "mss": ""},
        {"name": "Two Romantic Tales", "page": 872, "mss": ""},
        {"name": "Prophecy of Merlin", "page": 292, "mss": ""},
        {"name": "Prophecies de Merlin", "page": 371, "mss": ""},
        {"name": "The Chaste Duchess", "page": 713, "mss": ""},
        {"name": "Romances and Ballads", "page": 817, "mss": ""},
        {"name": "Robin Hood", "page": 519, "mss": ""},
        {"name": "Sir Lancelot of Dulake", "page": 397, "mss": ""},
        {"name": "Miscellaneous Ballads", "page": 525, "mss": ""},
        {"name": "The Grene Knight, turke and Gowin, The Marriage of Sir Gawaine", "page": 389, "mss": ""},
        {"name": "Sir Lambewell", "page": 417, "mss": ""},
        {"name": "Merlin", "page": 386, "mss": ""},
        {"name": "King ARthur's Death", "page": 406, "mss": ""},
        {"name": "Guye and Amarant", "page": 499, "mss": ""},
        {"name": "Three Ballads of Forest Life", "page": 523, "mss": ""},
        {"name": "Guy and Phillis", "page": 500, "mss": ""},
        {"name": "Robin Hood Ballad", "page": 520, "mss": ""},
        {"name": "Boy and Mantle", "page": 404, "mss": "27879 ff 140, 141"},
        {"name": "Libius Disconius", "page": 401, "mss": "27879 ff 156 b-171"},
        {"name": "Guy and Colebrande", "page": 500, "mss": "27879 ff 172 b-176b"},
        {"name": "Two Ballads relating to Adam Bell", "page": 522, "mss": "27879 ff 194-201"},
        {"name": "A Propecye", "page": 327, "mss": "27879 f 239 b"},
        {"name": "King Humber", "page": 339, "mss": "27879 f 248"},
        {"name": "Robin Hood's Garland", "page": 520, "mss": "28638"},
        {"name": "Ballads of Scotland", "page": 537, "mss": "29408, 29409"},
        {"name": "Roman de Troie", "page": 924, "mss": "30863"},
        {"name": "Voeux du Paon", "page": 926, "mss": "30864"},
        {"name": "Titurel", "page": 932, "mss": "30984"},
        {"name": "Titus and Vespasion", "page": 928, "mss": "31042 ff 50-66"},
        {"name": "Two Charlemagne Romances", "page": 953, "mss": "31042 ff 66 b-79 b, 82-94"},
        {"name": "Richard Coeur-de-Lion", "page": 944, "mss": "31042 ff 125-163 b"},
        {"name": "Roman de la Rose", "page": 884, "mss": "31 840"}
    ],

    "Egerton": [ # CORRIGE
        {"name": "Prophecy of the Tenth Sibyl", "page": 190, "mss": "810 ff 106-109 b"}, 
        {"name": "Roman de la Rose", "page": 879, "mss": "881"}, 
        {"name": "Tristram", "page": 362, "mss": "989"}, 
        {"name": "Roman de la Rose", "page": 890, "mss": "1069"},
        {"name": "Roman de la Rose", "page": 891, "mss": "2022"},
        {"name": "Ipomedon and Prothesilaus", "page": 746, "mss": "2515 ff 3-141"} 
    ]
}